language: node_js
matrix:
  include:
    - node_js: "0.10"
      env: _CXXAUTO=1
    - node_js: "0.12"
      env: _CXXAUTO=1
    - node_js: "4.2"
      env: CXX=g++-4.8
    - node_js: "5.0"
      env: CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
cache:
  directories:
    - node_modules
