#!/bin/sh

SCRIPT_PATH=`pwd`/$0

# here we append lib location to the node's lib

#echo $SCRIPT_PATH

# NODE_PATH=/usr/local/lib/node_modules/
UNAMES=`uname -s`

IS_WINDOWS=

OS_NAME=${UNAMES%%-*}
OS_VERS=${UNAMES##*-}

if [ "x$OS_NAME" == "xMINGW32_NT" ] ; then
	IS_WINDOWS=$OS_VERS
	DNS=`netsh interface ip show dns | grep 'DNS ser'  | cut -d ':' -f 2 | cut -d ' ' -f 3`
	echo nameserver $DNS > /etc/resolv.conf
fi

#echo "!!!!!!!!!!!!!!! $AAA !!!!!!!!!!!!!!!!!! $BBB !!!!!!!!!!!!!!!!!"

NODE_PATH=''

if [ "x$IS_WINDOWS" == "x" ] ; then
	NODE_PATH=/usr/local/lib/node_modules/
fi

NODE_PATH_DELIMITER=":"

#if [ "x$NODE_PATH" == "x" ] ; then
#	NODE_PATH_DELIMITER=""
#fi

#if [ "x$IS_WINDOWS" != "x" ] ; then
#	NODE_PATH_DELIMITER=":"
#fi


PROJECT_DIR=${SCRIPT_PATH%%bin/node}

if [ "x$1" == "x--project-root" ] ; then
	echo $PROJECT_DIR
	exit
fi

# echo $PROJECT_DIR

if [ "x$IS_WINDOWS" != "x" ] ; then
	PROJECT_DIR="/cygdrive$PROJECT_DIR"
fi

NODE_PATH=.$NODE_PATH_DELIMITER$NODE_PATH$NODE_PATH_DELIMITER${PROJECT_DIR}lib$NODE_PATH_DELIMITER${PROJECT_DIR}lib/workflow.nodejs

# echo $NODE_PATH

if [ "x$1" == "x" ] ; then
	NODE_PATH=$NODE_PATH /usr/bin/env node ${PROJECT_DIR}lib/workflow.nodejs/repl.js
else
	NODE_PATH=$NODE_PATH /usr/bin/env node $@
fi
